/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.form;

import controller.Controller;
import javax.swing.JDialog;

/**
 *
 * @author student1
 */
public class FMain extends javax.swing.JFrame {

    //private final Controller controller;
    /**
     * Creates new form FMain
     */
    public FMain() {
        initComponents();

        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        
        //controller = new Controller();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar = new javax.swing.JMenuBar();
        jMenuProduct = new javax.swing.JMenu();
        jMenuItemProductNew = new javax.swing.JMenuItem();
        jMenuItemProductSearch = new javax.swing.JMenuItem();
        jMenuAbout = new javax.swing.JMenu();
        jMenuItemAboutSoftware = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Welcome");

        jMenuProduct.setText("Product");

        jMenuItemProductNew.setText("New");
        jMenuItemProductNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProductNewActionPerformed(evt);
            }
        });
        jMenuProduct.add(jMenuItemProductNew);

        jMenuItemProductSearch.setText("Search");
        jMenuItemProductSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemProductSearchActionPerformed(evt);
            }
        });
        jMenuProduct.add(jMenuItemProductSearch);

        jMenuBar.add(jMenuProduct);

        jMenuAbout.setText("About");

        jMenuItemAboutSoftware.setText("Software");
        jMenuAbout.add(jMenuItemAboutSoftware);

        jMenuBar.add(jMenuAbout);

        setJMenuBar(jMenuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemProductSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProductSearchActionPerformed
        JDialog form = new FProductSearch(this, true);
       
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItemProductSearchActionPerformed

    private void jMenuItemProductNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemProductNewActionPerformed
        JDialog form = new FProduct(this, true, ModeForm.ADD);
        form.setVisible(true);
    }//GEN-LAST:event_jMenuItemProductNewActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAbout;
    private javax.swing.JMenuBar jMenuBar;
    private javax.swing.JMenuItem jMenuItemAboutSoftware;
    private javax.swing.JMenuItem jMenuItemProductNew;
    private javax.swing.JMenuItem jMenuItemProductSearch;
    private javax.swing.JMenu jMenuProduct;
    // End of variables declaration//GEN-END:variables
}
